name: Build and Deploy Docusaurus to Azure Static Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docusaurus site
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Change directory to my-doc-site
        run: cd my-doc-site

      - name: Install dependencies
        run: npm install
        working-directory: my-doc-site

      - name: Build Docusaurus
        run: npm run build
        working-directory: my-doc-site

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: docusaurus-build
          path: my-doc-site/build/

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web Apps
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: docusaurus-build
          path: build

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          output_location: "build"
